Organizations:
    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: crypto-config/ordererOrganizations/example.com/msp
    - &Orguidai
        Name: OrguidaiMSP
        ID: OrguidaiMSP
        MSPDir: crypto-config/peerOrganizations/orguidai.example.com/msp
        AnchorPeers:
            - Host: peer0.orguidai.example.com
              Port: 7051
    - &Orgdl
        Name: OrgdlMSP
        ID: OrgdlMSP
        MSPDir: crypto-config/peerOrganizations/orgdl.example.com/msp
        AnchorPeers:
            - Host: peer0.orgdl.example.com
              Port: 7051
    - &Orgpp
        Name: OrgppMSP
        ID: OrgppMSP
        MSPDir: crypto-config/peerOrganizations/orgpp.example.com/msp
        AnchorPeers:
            - Host: peer0.orgpp.example.com
              Port: 7051
    - &Orgpan
        Name: OrgpanMSP
        ID: OrgpanMSP
        MSPDir: crypto-config/peerOrganizations/orgpan.example.com/msp
        AnchorPeers:
            - Host: peer0.orgpan.example.com
              Port: 7051

Application: &ApplicationDefaults
    Organizations:

Orderer: &OrdererDefaults
    OrdererType: solo
    Addresses:
        - orderer.example.com:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Kafka:
        Brokers:
            - 127.0.0.1:9092
    Organizations:

Profiles:

    OrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Orgdl
                    - *Orgpan
                    - *Orguidai
                    - *Orgpp

    Channel_dl_uidai:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Orgdl
                - *Orguidai

    Channel_pp_uidai:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Orgpp
                - *Orguidai
    
    Channel_pan_uidai:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Orguidai
                - *Orgpan

