OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Orguidai
    Domain: orguidai.example.com
    Template:
      Count: 1                            #NUMBER OF PEERS
    Users:
      Count: 1                            #NUMBER OF USERS APART FROM THE ADMIN
  - Name: Orgdl
    Domain: orgdl.example.com
    Template:
      Count: 1                            #NUMBER OF PEERS
    Users:
      Count: 1                            #NUMBER OF USERS APART FROM THE ADMIN
  - Name: Orgpp
    Domain: orgpp.example.com
    Template:
      Count: 1                            #NUMBER OF PEERS
    Users:
      Count: 1                            #NUMBER OF USERS APART FROM THE ADMIN
  - Name: Orgpan
    Domain: orgpan.example.com
    Template:
      Count: 1                            #NUMBER OF PEERS
    Users:
      Count: 1                            #NUMBER OF USERS APART FROM THE ADMIN

