Organizations:
    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: crypto-config/ordererOrganizations/example.com/msp

    - &Orguidai
        Name: OrguidaiMSP
        ID: OrguidaiMSP
        MSPDir: crypto-config/peerOrganizations/orguidai.example.com/msp
        AnchorPeers:
            - Host: peer0.orguidai.example.com
              Port: 7051

    - &Orgdl
        Name: OrgdlMSP
        ID: OrgdlMSP
        MSPDir: crypto-config/peerOrganizations/orgdl.example.com/msp
        AnchorPeers:
            - Host: peer0.orgdl.example.com
              Port: 7051

Orderer: &OrdererDefaults
    OrdererType: solo
    Addresses:
        - orderer.example.com:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB

    Kafka:
        Brokers:
            - 127.0.0.1:9092
    Organizations:

Application: &ApplicationDefaults
    Organizations:

Profiles:
    OrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Orguidai
                    - *Orgdl
                    
    ChannelOrgUidai:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Orguidai

    ChannelBothOrgs:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Orguidai
                - *Orgdl

