version: '2'

networks:
  custom_network:
    external:
      name: trial_net

services:
  ca.example.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.example.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/*_sk
    ports:
      - 7054:7054
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/ordererOrganizations/example.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ./crypto-config/ordererOrganizations/example.com/ca/:/etc/hyperledger/fabric-ca-server/msp/keystore
    container_name: ca.example.com
    networks:
      custom_network:
        aliases:
          - ca.example.com
    # deploy:
    #         mode: replicated
    #         replicas: 1
    #         restart_policy:
    #           condition: on-failure
    #         placement:
    #             constraints:
    #                 - node.hostname == node1

  orderer.example.com:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 7050:7050
    volumes:
      - ./config/:/etc/hyperledger/configtx
      - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/:/etc/hyperledger/msp/orderer
      - ./crypto-config/peerOrganizations/orgdl.example.com/peers/peer0.orgdl.example.com/:/etc/hyperledger/msp/peerOrgdl
      - ./crypto-config/peerOrganizations/orguidai.example.com/peers/peer0.orguidai.example.com/:/etc/hyperledger/msp/peerOrguidai
    networks:
      custom_network:
        aliases:
          - orderer.example.com
    # deploy:
    #         mode: replicated
    #         replicas: 1
    #         restart_policy:
    #           condition: on-failure
    #         placement:
    #             constraints:
    #                 - node.hostname == node1 


