

OrdererOrgs:
  - Name: orderer
    Domain: seva.gov.in
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: dl
    Domain: dl.seva.gov.in
    EnableNodeOUs: true
    Template:
      Count: 3                            #NUMBER OF PEERS
    Users:
      Count: 2                            #NUMBER OF USERS APART FROM THE ADMIN

