

OrdererOrgs:
  - Name: orderer
    Domain: example.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: dl
    Domain: dl.example.com
    EnableNodeOUs: true
    Template:
      Count: 3                            #NUMBER OF PEERS
    Users:
      Count: 2                            #NUMBER OF USERS APART FROM THE ADMIN

