NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.dl.seva.gov.in-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.dl.seva.gov.in-cert.pem
    OrganizationalUnitIdentifier: peer
